### ISSUE TITLE
Error in parsing FEN

### ISSUE THREAD

**Issue by appletomato** [jhlywa/chess.js#216]
There is an error in parsing FENs. Steps to reproduce:

1. chess.load("r1bqkbnr/pp1npppp/3p4/1Bp5/4P3/2P2N2/PP1P1PPP/RNBQK2R b KQkq - 0 4")
2. chess.move("Ngf6")
3. chess.fen()

Output: 
"r1bqkbnr/pp1npppp/3p4/1Bp5/4P3/2P2N2/PP1P1PPP/RNBQK2R b KQkq - 0 4". i.e., no move has been made

Expected output:
"r1bqkb1r/pp1npppp/3p1n2/1Bp5/4P3/2P2N2/PP1P1PPP/RNBQK2R b KQkq - 1 5", since Ngf6 is a valid move in the position.

EDIT: Seems to work with the "sloppy" option, though.

**Comment by thearst3rd** [comment]
The reason Ngf6 is not valid is because Nf6 is actually not ambiguous. The Knight on the d file is not allow to move to f6, because it is pinned by the Bishop, and moving it would put black's king in check.

I've imported the FEN into Lichess and performed the move, and Lichess reports that the move is simply "Nf6". You can try it here:
https://lichess.org/analysis/standard/r1bqkbnr/pp1npppp/3p4/1Bp5/4P3/2P2N2/PP1P1PPP/RNBQK2R_b_KQkq_-_0_4#7
