### ISSUE TITLE
How attacked function work?

### ISSUE THREAD

**Issue by kaisukez** [jhlywa/chess.js#230]
I don't understand what ATTACKS, SHIFTS and RAYS variables do.

For this lines of code
```js
    var difference = i - square
    var index = difference + 119
```
What does `i - square` means?
And what ` i - square + 119` do?

After reading [this](https://www.chessprogramming.org/Attack_and_Defend_Maps) and [this](https://www.chessprogramming.org/Rays) article, I still have no idea. There're many algorithms in that article with little explanation and there's no relation between them, such as what RAYS have something to do with ATTACKS and SHIFTS and so on.

Can someone explain in detail or tell me exact keywords that I can search for, like what exactly the name of this algorithm or links to article or forum.

Thanks.

**Comment by jhlywa** [comment]
A lot of people are confused when they first see the internal representation of chess.js.  It uses the [0x88 Move Generation Algorithm](https://www.chessprogramming.org/0x88) which internally stores the board as an 8x16 array.  This is purely for efficiency but has a couple of interesting benefits:

1. It offers a very inexpensive "off the board" check.   Bit-wise AND any square with 0x88, if the result is non-zero then the square is off the board.  For example, assuming a knight square A8 (0 in 0x88 notation), there are 8 possible squares to which the knight can move.  One of these square is A8 - 18 (up on square, and to the left two square - which is off the board).  0 - 18 = -18 & 0x88 = 0x88 (because of two-complement representation of -18).  The non-zero result means the square is off the board and the move is illegal.  Take the opposite move (from A8 to  C7), 0 + 18 = 18 & 0x88 = 0.  A zero result means the square is on the board.

2.  The relative distance (or `difference`) between two squares on a 0x88 board is unique and can be used to  inexpensively determine if a piece on a square can attack any other arbitrary square.  For example, let's see if a pawn on E7 can attack E2.  The difference between E7 (20) - E2 (100) is -80.  We add `119` to make the `ATTACKS` array index non-negative (because the worst case difference is A8 - H1 = -119) The `ATTACKS` array contains a bitmask of pieces that can attack from that distance and direction.  `ATTACKS[-80 + 119=39]` which gives of `24` or `11000` in binary.  Look at the `SHIFTS` map to determine the piece masking.  In our pawn example, we would check to see if 24 & (1 << 0) is non-zero, which it is not.  So a pawn on E7 can't attack a piece on E2.  However, a rook can since  24 & (1 << 3) is non-zero.  The `RAYS` array simple allows us to traverse the distance between the two squares checking for any blocking pieces.

I hope that helps.

**Comment by kaisukez** [comment]
Thanks for spending your time answering me. Now I understand the idea and it's quite elegant one.
