### ISSUE TITLE
Validaiton for only one king

### ISSUE THREAD

**Issue by HikeGrig** [jhlywa/chess.js#273]
How i can check if there is only one king in board?

**Comment by bhx4874** [comment]
This probably isn't an option because the game will end when a king is checkmated, meaning that there will always two kings on the board and you can't take a king. Unless you're doing so weird puzzle or making a custom game/setup this scenario will not show up. However to check for one king, you can probably search the FEN string for a single instance of K. For example, rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR has two Ks so you know both kings are still on the board. If you can explain why you're asking this question I might be able to give you a better answer.

**Comment by HikeGrig** [comment]
> This probably isn't an option because the game will end when a king is checkmated, This means that there will always two kings on the board and the game won't let you take a king. Unless you're doing so weird puzzle or making a custom game/setup, this scenario will not show up. However to check for one king, you can probably search the FEN string for a single instance of K. For example, rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR has two Ks so you know both kings are still on the board. If you can explain why you're asking this question, I might be able to help provide a better answer.

Yes i create functional to making a custom game/setup, after user created it i should check is there two kings, if not i should display error. I didn't found any method that can check that situation.

**Comment by jhlywa** [comment]
@HikeGrig This sort of thing should probably be wrapped into the API, but as a quick hack:
```js
const numOfKings = chess.fen().split(' ')[0].match(/k|K/g)
```
