### ISSUE TITLE
Calculate previous FEN from current FEN and last move

### ISSUE THREAD

**Issue by Nikola-Obreshkov** [jhlywa/chess.js#277]
Is there a way to get the previous FEN if I have the current FEN and I know what is the last move with Chess.js?

**Comment by ajax333221** [comment]
I'm trying to figure this and in the process I have noticed this:

`1. h4 h5 2. Rh2 Rh7 3. Nc3 Nc6 4. Rh1 Rh8 5. Nb1 Nb8 6. Rh2 Rh7`

Example 1 after **2... Rh7** = `"rnbqkbn1/pppppppr/8/7p/7P/8/PPPPPPPR/RNBQKBN1 w Qq - 2 3"`

Example 2 after **6... Rh7** = `"rnbqkbn1/pppppppr/8/7p/7P/8/PPPPPPPR/RNBQKBN1 w Qq - 10 7"`

If you use `chess.undo()` then `chess.fen()` twice each time (to undo Rh7 and Rh2), the first time it will correctly turn into `"Qkq and KQkq"` while the second time it will stay `"Qq and Qq"` as expected.

However, I fail to see what part from the move flags are being used in order to achieve this or if there is something elsewhere being stored and it's being used.

I don't know why I am posting this as it doesn't solve anything, but yea idk... sorry.

**Comment by jhlywa** [comment]
@Nikola-Obreshkov If you've got the whole move history in chess.js you can use `.undo()` to undo the last move and then simply grab the FEN with `.fen()`.  If all you have is the _last_ move, then no.  You might be able to reconstruct the original position, but the castling and en passant flags within the FEN would be undefined.

**Comment by jhlywa** [comment]
@ajax333221 The castling flags are set initially on `.new()` and `.load()` and decumulated as moves are played (https://github.com/jhlywa/chess.js/blob/master/chess.js#L920-L965).

The data returned in the move object is purely metadata. I don't think it's worth including castling states, the ep square, and the halfmove counter within this object - after all, if you have a move object then you probably have the whole history loaded at that point.

**Comment by Nikola-Obreshkov** [comment]
I have only a FEN and the last move. It seems I cannot get the previous FEN from this. In fact I don't need the whole previous FEN only the position part. I know it is doable but I was curios if there is some utility in chess.js to do it. It seems there is not. Thank you for the responses.

**Comment by jhlywa** [comment]
Even constructing the original position would be difficult.  Say you have the move 'Qd4', how would you know from which square the queen originated?  Or, maybe you have long algebraic notation 'd1xd4' (a capture), how would you know which piece was captured?  Sorry, I don't think it is possible.

**Comment by Nikola-Obreshkov** [comment]
In my case I use JSON and I have control how much information is stored for every move. The source square and the captured piece can be added as part of the move information. However, it is clear now that such a functionality was not expected to be present as it will not work in the general case as you pointed out.
