### ISSUE TITLE
load_pgn duplicates last half-move if it has a comment

### ISSUE THREAD

**Issue by vonschultz** [jhlywa/chess.js#279]
If there's a comment on the last half-move, load_pgn will duplicate that move, which either results in returning "false" (if it wasn't a legal move) or an actual duplicate ending up in the history.

Example:
```
testgame = new Chess()
testgame.load_pgn("1. e4 e5 2. Nf3 Nc6 3. Bb5 d6 4. d4 Bd7 5. Nc3 Nf6 6. Bxc6 {comment}")
```
Now `testgame.history()` returns `["e4","e5","Nf3","Nc6","Bb5","d6","d4","Bd7","Nc3","Nf6","Bxc6","Bxc6"]`. Notice the extra `Bxc6` at the end, which happens to be a legal move in this position.

If you do
```
testgame = new Chess()
testgame.load_pgn("1. e4 e5 2. Nf3 Nc6 3. Bb5 d6 4. d4 Bd7 5. Nc3 Nf6 6. Bxc6")
```
then `testgame.history()` will instead be `["e4","e5","Nf3","Nc6","Bb5","d6","d4","Bd7","Nc3","Nf6","Bxc6"]`, which is the expected value for both these examples.

**Comment by bhx4874** [comment]
I believe that Bxc6 duplicated because chess,js couldn't read your notation. The * symbol is used at the end of a game to signify an incomplete game. I haven't worked with chess,js for too long, but I assume that the ] is enough to denote the end of the PGN. I guessing that since chess.js didn't see a move for the other player after Bxc6, it made a move just to have a complete move pair. `'1. e4 e5 2. Nf3 Nc6 3. Bb5 d6 4. d4 Bd7 5. Nc3 Nf6 6. Bxc6 {comment} *'` fixed the issue for me.

**Comment by jhlywa** [comment]
Thanks for the report.  This is fixed in master.
