### ISSUE TITLE
Feature Request: Timestamping when making a move

### ISSUE THREAD

**Issue by zekicaneksi** [jhlywa/chess.js#339]
when making a move, it would be very nice if we could timestamp the move. Or better yet, if we could give any other properties to the move object.

I wanted to help you and do it myself but couldn't understand the chess.js file. Can you maybe give me some pointers so i can help you implement this feature? For instance what's the flow of the functions when making a move and getting the history?

I tried to add the timestamp property to the build_move function, and when printing history i can see it but i can't set it. I looked at the make_pretty, and push functions as well but just couldn't figure it out.

Thanks

**Comment by bpalmer661** [comment]
if you are looking to make an online game like www.chessbettingonline.com you need to time stamp in the server because time stamps on the computer will differ slightly from computer to computer,    but a server timestamp will be the same for both players.        also you can just create your own object and add a timestamp along with the chess.fen() ,
