### ISSUE TITLE
BUG: Single Square Move Generation

### ISSUE THREAD

**Issue by DioBrandoZ** [jhlywa/chess.js#341]
a1、 h1 square are not rook，but can castle

```
{
  fen: 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/Q3K2N w KQkq - 0 1',
  square: 'e1',
  verbose: false,
  moves: ['kf1', 'kd1'],
}
```

expected:  ['Kf1', 'Kd1'],
received:   [ "Kf1",  "Kd1", "O-O",   "O-O-O" ]

yarn test result : 

![image](https://user-images.githubusercontent.com/28890682/181717480-4ffc189a-3b85-4816-bac4-0343f920df9e.png)

**Comment by jhlywa** [comment]
Thanks for the report @DioBrandoZ.  This occurs because the provided FEN contains castling rights (the 'KQkq' portion of the string) which makes the library think it can castle.  The next version of chess.js will contain more sophisticated FEN validation that throw errors when loading FEN that contains errors/mistakes.

To work around this issue try using this FEN instead: `rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/Q3K2N w kq - 0 1`
