### ISSUE TITLE
chess.js into client side

### ISSUE THREAD

**Issue by AlonsoDo** [jhlywa/chess.js#405]
In a Node.js environment the new 1.0.0 versions of chess.js work fine on the server side.
But how do I make it work on the client side? What are the steps to follow? I can't find documentation.
What about CDN and instance declaration with var chess = new Chess(); .
Is there any other way to do it?

**Comment by jhlywa** [comment]
@AlonsoDo I believe you're running into this issue due to the differences between ESM vs CommonJS [more info here](https://github.com/jhlywa/chess.js/issues/335#issuecomment-1518423758). Sorry for the lame answer, but maybe try using a bundler (webpack or rollup)? There are a couple of things I'd like to try to support both environments, but my development time is extremely limited for the next few weeks.

**Comment by jhlywa** [comment]
This issue has been fixed in 1.0.0-beta.6.  See the README for more info.
