### ISSUE TITLE
What do the last characters returned by the fen function mean?

### ISSUE THREAD

**Issue by aRmaz0n** [jhlywa/chess.js#429]
```
chess.fen()
// -> 'rnbqkbnr/pppp1ppp/8/4p3/4PP2/8/PPPP2PP/RNBQKBNR b KQkq - 0 2'
```

these --> KQkq - 0 2

**Comment by jhlywa** [comment]
Hi @aRmaz0n,

- `KQkq` indicates castling availability (both colors are still able to castle queen/kingside)
- `-` means there is no en passant square
- `0` is the half move counter (the number of half moves since the last capture or pawn move)
- `2` the move number

See more here:
https://en.wikipedia.org/wiki/Forsyth-Edwards_Notation
